/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import javax.swing.JOptionPane;

/**
 *
 * @author komal
 */
public class Home extends javax.swing.JFrame {

    public String email;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    public Home(String useremail) {
        initComponents();
        email = useremail;
        if (!email.equals("admin@gmail.com")) {
            btncategory.setVisible(false);
            btnnewproduct.setVisible(false);
            btnvieweditdeleteproduct.setVisible(false);
            btnverifyusers.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btncategory = new javax.swing.JButton();
        btnnewproduct = new javax.swing.JButton();
        btnvieweditdeleteproduct = new javax.swing.JButton();
        btnverifyusers = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncategory.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        btncategory.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\category.png")); // NOI18N
        btncategory.setText("MANAGE CATEGORY");
        btncategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btncategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 710, -1, -1));

        btnnewproduct.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        btnnewproduct.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\new product.png")); // NOI18N
        btnnewproduct.setText("NEW PRODUCT");
        btnnewproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewproductActionPerformed(evt);
            }
        });
        getContentPane().add(btnnewproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 710, -1, -1));

        btnvieweditdeleteproduct.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        btnvieweditdeleteproduct.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\view edit delete product.png")); // NOI18N
        btnvieweditdeleteproduct.setText("VIEW,EDIT,DELETE PRODUCT");
        btnvieweditdeleteproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvieweditdeleteproductActionPerformed(evt);
            }
        });
        getContentPane().add(btnvieweditdeleteproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 710, -1, -1));

        btnverifyusers.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        btnverifyusers.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\verify users.png")); // NOI18N
        btnverifyusers.setText("VERIFY USERS");
        btnverifyusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifyusersActionPerformed(evt);
            }
        });
        getContentPane().add(btnverifyusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 710, -1, -1));

        jButton2.setFont(new java.awt.Font("Bell MT", 2, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\place order.png")); // NOI18N
        jButton2.setText("PLACE ORDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jButton3.setFont(new java.awt.Font("Bell MT", 2, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\View Bills & Order Placed Details.png")); // NOI18N
        jButton3.setText("VIEW BILL & ORDER PLACED DETAILS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jButton4.setFont(new java.awt.Font("Bell MT", 2, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\change Password.png")); // NOI18N
        jButton4.setText("CHANGE PASSWORD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        jButton5.setFont(new java.awt.Font("Bell MT", 2, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\change Security Question.png")); // NOI18N
        jButton5.setText("CHANGE SECURITY QUESTION");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 280, -1));

        btnexit.setFont(new java.awt.Font("Bell MT", 2, 14)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\exit.png")); // NOI18N
        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 110, -1));

        btnlogout.setFont(new java.awt.Font("Bell MT", 2, 14)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\logout.png")); // NOI18N
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\home-background-image.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        new ChangePassword(email).setVisible(true);
    }                                        

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Logout", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }                                         

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Close Application", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }                                       

    private void btncategoryActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        new ManageCategory().setVisible(true);
    }                                           

    private void btnnewproductActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        new AddNewProduct().setVisible(true);
    }                                             

    private void btnvieweditdeleteproductActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
        new ViewEditDeleteProduct().setVisible(true);
    }                                                        

    private void btnverifyusersActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        new VerifyUsers().setVisible(true);
    }                                              

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
        setVisible(false);
        new PlaceOrder(email).setVisible(true);
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        new ViiewBillOrderPlaceDetails().setVisible(true);
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        new ChangeSecurityQuestion(email).setVisible(true);   
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btncategory;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnnewproduct;
    private javax.swing.JButton btnverifyusers;
    private javax.swing.JButton btnvieweditdeleteproduct;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
