/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;
import dao.BillDao;
import dao.CategoryDao;
import dao.ProductDao;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Bill;
import model.Category;
import model.Product;

/**
 *
 * @author komal
 */
public class PlaceOrder extends javax.swing.JFrame {

    public int billId = 1;
    public int grandtotal = 0;
    public int productprice = 0;
    public int producttotal = 0;
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobnoPattern = "^[0-9]*$";
    public String userEmail;

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
    }

    public PlaceOrder(String email) {
        initComponents();
        txtproductname.setEditable(false);
        txtproductprice.setEditable(false);
        txtproductotal.setEditable(false);
        btnaddtocart.setEnabled(false);
        btngeneratebill.setEnabled(false);
        JFormattedTextField tf = ((JSpinner.DefaultEditor) jSpinner1.getEditor()).getTextField();
        tf.setEditable(false);
        userEmail = email;
    }

    public void productnameByCategory(String category) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list = ProductDao.getAllRecordsByCategory(category);
        Iterator<Product> itr = list.iterator();
        while (itr.hasNext()) {
            Product productobj = itr.next();
            dtm.addRow(new Object[]{productobj.getName()});
        }
    }

    public void filterProductByname(String name, String category) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list = ProductDao.filterProductByname(name, category);
        Iterator<Product> itr = list.iterator();
        while (itr.hasNext()) {
            Product productobj = itr.next();
            dtm.addRow(new Object[]{productobj.getName()});
        }
    }

    public void clearproductFields() {
        txtproductname.setText("");
        txtproductprice.setText("");
        txtproductotal.setText("");
        jSpinner1.setValue(1);
        btnaddtocart.setEnabled(false);
    }

    public void validateFields() {
        String customername = txtcustomername.getText();
        String customermobno = txtcustomermobno.getText();
        String customeremail = txtcustomeremail.getText();
        if (!customeremail.equals("") && customermobno.matches(mobnoPattern) && customermobno.length() == 10 && customeremail.matches(emailPattern) && grandtotal > 0) {
            btngeneratebill.setEnabled(true);
        } else {
            btngeneratebill.setEnabled(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcustomername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcustomermobno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcustomeremail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtproductname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtproductprice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        txtproductotal = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        btnaddtocart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        lblgrandtotal = new javax.swing.JLabel();
        btngeneratebill = new javax.swing.JButton();
        label17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\place order.png")); // NOI18N
        jLabel1.setText("PLACE ORDER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 219, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\close.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BILL ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 88, 81, -1));

        jLabel3.setText("--");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 91, 30, -1));

        jLabel4.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        jLabel4.setText("CUSTOMER DETAILS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 142, 201, -1));

        jLabel5.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        jLabel5.setText("NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 71, -1));

        txtcustomername.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        txtcustomername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcustomernameKeyReleased(evt);
            }
        });
        getContentPane().add(txtcustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 269, 201, 30));

        jLabel6.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        jLabel6.setText("MOB NO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 85, -1));

        txtcustomermobno.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        txtcustomermobno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomermobnoActionPerformed(evt);
            }
        });
        txtcustomermobno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcustomermobnoKeyReleased(evt);
            }
        });
        getContentPane().add(txtcustomermobno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 201, 30));

        jLabel7.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        jLabel7.setText("EMAIL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 465, 71, -1));

        txtcustomeremail.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        txtcustomeremail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcustomeremailKeyReleased(evt);
            }
        });
        getContentPane().add(txtcustomeremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 201, 30));

        jLabel8.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        jLabel8.setText("CATEGORY");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 88, 109, -1));

        jComboBox1.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 139, 291, -1));

        jLabel9.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        jLabel9.setText("SEARCH");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 192, 87, -1));

        txtsearch.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 241, 291, 35));

        jTable1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 327, 328, 397));

        jLabel10.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        jLabel10.setText("NAME");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 88, -1, -1));

        txtproductname.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        getContentPane().add(txtproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 139, 200, -1));

        jLabel11.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        jLabel11.setText("PRICE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1125, 88, 62, -1));

        txtproductprice.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        getContentPane().add(txtproductprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 139, 200, -1));

        jLabel12.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        jLabel12.setText("QUANTITY");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 192, 111, -1));

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 200, 30));

        jLabel13.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        jLabel13.setText("TOTAL");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1123, 192, 74, -1));

        txtproductotal.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        getContentPane().add(txtproductotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 245, 200, -1));

        btnclear.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\clear.png")); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 309, -1, 30));

        btnaddtocart.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnaddtocart.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\add to cart.png")); // NOI18N
        btnaddtocart.setText("ADD TO CART");
        btnaddtocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddtocartActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddtocart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1094, 309, -1, 30));

        jTable2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "PRICE", "QUANTITY", "TOTAL"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, -1, 338));

        jLabel14.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        jLabel14.setText("GRAND TOTAL : Rs.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 730, -1, -1));

        lblgrandtotal.setFont(new java.awt.Font("Bell MT", 2, 18)); // NOI18N
        lblgrandtotal.setText("000");
        getContentPane().add(lblgrandtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 730, 37, -1));

        btngeneratebill.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btngeneratebill.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\generate bill & print.png")); // NOI18N
        btngeneratebill.setText("GENERATE BILL & PRINT");
        btngeneratebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeneratebillActionPerformed(evt);
            }
        });
        getContentPane().add(btngeneratebill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 720, -1, -1));

        label17.setIcon(new javax.swing.ImageIcon("C:\\Users\\komal\\OneDrive\\Documents\\NetBeansProjects\\Cafe Management System\\Cafe Image & Icon\\images\\full-page-background.PNG")); // NOI18N
        getContentPane().add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>                        

    private void txtcustomermobnoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnaddtocartActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        String name = txtproductname.getText();
        String price = txtproductprice.getText();
        String quantity = String.valueOf(jSpinner1.getValue());
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.addRow(new Object[]{name, price, quantity, producttotal});
        grandtotal = grandtotal + producttotal;
        lblgrandtotal.setText(String.valueOf(grandtotal));
        clearproductFields();
        validateFields();
    }                                            

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        setVisible(false);
        new Home(userEmail).setVisible(true);
    }                                        

    private void formComponentShown(java.awt.event.ComponentEvent evt) {                                    
        // TODO add your handling code here:
        billId = Integer.parseInt(BillDao.getId());
        jLabel3.setText(BillDao.getId());
        ArrayList<Category> list = CategoryDao.getAllRecords();
        Iterator<Category> itr = list.iterator();
        while (itr.hasNext()) {
            Category categoryobj = itr.next();
            jComboBox1.addItem(categoryobj.getName());
        }
        String category = (String) jComboBox1.getSelectedItem();
        productnameByCategory(category);
    }                                   

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        String name = txtsearch.getText();
        String category = (String) jComboBox1.getSelectedItem();
        filterProductByname(name, category);
    }                                     

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String productname = model.getValueAt(index, 0).toString();
        Product product = ProductDao.getProductByname(productname);
        txtproductname.setText(product.getName());
        txtproductprice.setText(product.getPrice());
        jSpinner1.setValue(1);
        txtproductotal.setText(product.getPrice());
        productprice = Integer.parseInt(product.getPrice());
        producttotal = Integer.parseInt(product.getPrice());
        btnaddtocart.setEnabled(true);
    }                                    

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {                                       
        // TODO add your handling code here:
        int quantity = (Integer) jSpinner1.getValue();
        if (quantity <= 1) {
            jSpinner1.setValue(1);
            quantity = 1;
        }
        producttotal = productprice * quantity;
        txtproductotal.setText(String.valueOf(producttotal));
    }                                      

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        String category = (String) jComboBox1.getSelectedItem();
        productnameByCategory(category);
    }                                          

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        clearproductFields();
    }                                        

    private void txtcustomernameKeyReleased(java.awt.event.KeyEvent evt) {                                            
        // TODO add your handling code here:
        validateFields();
    }                                           

    private void txtcustomermobnoKeyReleased(java.awt.event.KeyEvent evt) {                                             
        // TODO add your handling code here:
        validateFields();
    }                                            

    private void txtcustomeremailKeyReleased(java.awt.event.KeyEvent evt) {                                             
        // TODO add your handling code here:
        validateFields();
    }                                            

    private void btngeneratebillActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        String customername = txtcustomername.getText();
        String customermobno = txtcustomermobno.getText();
        String customeremail = txtcustomeremail.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        String todaydate = dFormat.format(date);
        String total = String.valueOf(grandtotal);
        String createdBy = userEmail;
        Bill bill = new Bill();
        bill.setId(billId);
        bill.setName(customername);
        bill.setMobno(customermobno);
        bill.setEmail(customeremail);
        bill.setDate(todaydate);
        bill.setTotal(total);
        bill.setCreatedBy(createdBy);
        BillDao.save(bill);

        //creating document
        String path = "Downloads";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + billId + ".pdf"));
            doc.open();
            Paragraph cafeName = new Paragraph("                       CAFE MANAGEMENT SYSTEM\n");
            doc.add(cafeName);
            Paragraph starLine = new Paragraph("********************************************************");
            doc.add(starLine);
            Paragraph paragraph3 = new Paragraph("\tBill ID:" + billId + "\nCustomer Name:" + customername + "\nTotal Paid:" + grandtotal);
            doc.add(paragraph3);
            doc.add(starLine);
            PdfPTable tb1 = new PdfPTable(4);
            tb1.addCell("Name");
            tb1.addCell("Price");
            tb1.addCell("Quantity");
            tb1.addCell("Total");
            for (int i = 0; i < jTable2.getRowCount(); i++) {
                String n = jTable2.getValueAt(i, 0).toString();
                String d = jTable2.getValueAt(i, 1).toString();
                String r = jTable2.getValueAt(i, 2).toString();
                String q = jTable2.getValueAt(i, 3).toString();
                tb1.addCell(n);
                tb1.addCell(d);
                tb1.addCell(r);
                tb1.addCell(q);
            }
            doc.add(tb1);
            doc.add(starLine);
            Paragraph thanksMsg = new Paragraph(" THANK YOU , PLEASE VISIT AGAIN");
            doc.add(thanksMsg);

            //open pdf
            OpenPdf.openById(String.valueOf(billId));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        setVisible(false);
        new PlaceOrder(createdBy).setVisible(true);
    }                                               

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        int index = jTable2.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to remove this product", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            TableModel model = jTable2.getModel();
            String total = model.getValueAt(index, 3).toString();
            grandtotal = grandtotal - Integer.parseInt(total);
            lblgrandtotal.setText(String.valueOf(grandtotal));
            ((DefaultTableModel) jTable2.getModel()).removeRow(index);
        }
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnaddtocart;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btngeneratebill;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel lblgrandtotal;
    private javax.swing.JTextField txtcustomeremail;
    private javax.swing.JTextField txtcustomermobno;
    private javax.swing.JTextField txtcustomername;
    private javax.swing.JTextField txtproductname;
    private javax.swing.JTextField txtproductotal;
    private javax.swing.JTextField txtproductprice;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration                   
}
